### ISSUE TITLE
joi.when() is not working 

### ISSUE THREAD

**Issue by preetampt57** [kenspirit/joi-route-to-swagger#11]
For joi.when() schema proper swagger definition is not coming for example 

Joi schema:- 
myRequiredField: rm.joi.boolean(),
message: rm.joi.when('myRequiredField', {
     is: true,
     then: rm.joi.string(),
     otherwise: rm.joi.number(),
})

Actual swagger definition:- 
  "myRequiredField": {
    "type": "boolean",
    "description": ""
  },
  "message": {
    "type": [
      "array",
      "boolean",
      "number",
      "object",
      "string",
      "null"
    ],
    "description": ""
  }

Expected swagger definition:-

  "myRequiredField": {
    "type": "boolean",
    "description": ""
  },
  "message": {
    "properties": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "number",
          "format": "number"
        }
      ]
    }
  }

**Comment by kenspirit** [comment]
@preetampt57 Thanks for submitting the issue.  The previous implementation does not take this conditional case into account.  I will check what is the best fit JSON schema for this kind of joi definition.

**Comment by kenspirit** [comment]
@preetampt57 Please use the version 1.2.0 which adopts the joi-to-json@1.4.1 to support this.  [Commit](https://github.com/kenspirit/joi-route-to-swagger/commit/9bd3ac42f77c5ae171f718ac0dfa6cd38f87d315)

**Comment by preetampt57** [comment]
joi-to-swagger can be used instead of joi-to-json.

Done in my local, now everything is working as expected
