### ISSUE TITLE
How to define upload api

### ISSUE THREAD

**Issue by preetampt57** [kenspirit/joi-route-to-swagger#12]
Is there any example to define an upload api?

**Comment by kenspirit** [comment]
@preetampt57 You can check the [sample](https://github.com/kenspirit/joi-route-to-swagger/blob/c3151e69ac5e3e53f0c303b3e498524f0260691c/test/fixtures/mockA-routes.js#L98) here.

It's simply using `joi.binary()` for the field and it will generate the API as multipart form for upload

**Comment by preetampt57** [comment]
Thanks it worked
