### ISSUE TITLE
Can't upload the file via swagger

### ISSUE THREAD

**Issue by anurag489** [kenspirit/joi-route-to-swagger#5]
Hello sir,

Can anyway to upload the multipart/form-data via joi_to_json_schema?

**Comment by kenspirit** [comment]
`joi.binary()` is the way to define a field for upload.  If the library detects that there is one field set as binary, it will change the form to use multipart @anurag489

**Comment by anurag489** [comment]
One more how can we do the versioning API like v1 and v2 in swagger?

**Comment by kenspirit** [comment]
@anurag489 Versioning is actually a matter of taste on how to define the routes.  The library does not enforce anything.  You can use the basePath or individual route for that.
